---
# https://docs.docker.com/engine/install/ubuntu/
# fingerprint 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
docker_key_url: https://download.docker.com/linux/ubuntu/gpg
docker_keyring: "{{ apt_keyring_dir }}/docker.asc"
docker_repo_uri: https://download.docker.com/linux/ubuntu

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

# containerd.io bundles containerd and runc.
docker_conflicting_packages:
  - docker.io
  - docker-compose
  - docker-compose-v2
  - docker-doc
  - podman-docker
  - containerd
  - runc
